#tomcat config
server:
  port: 8888
rsa:
  public: /Users/wdc/Develop/Tools/Rsa/rsa_public_key.pem
  private: /Users/wdc/Develop/Tools/Rsa/pkcs8_rsa_private_key.pem
spring:
  http:
    multipart:
      max-file-size: 5MB