CREATE TABLE IF NOT EXISTS `computer` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(45) NULL DEFAULT NULL,
	`brand` VARCHAR(10) NULL DEFAULT NULL,
	`type` TINYINT NULL DEFAULT NULL,
	`scale` VARCHAR(10) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);