CREATE TABLE IF NOT EXISTS `demo_young` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(45) NULL DEFAULT NULL,
	`sex` VARCHAR(10) NULL DEFAULT NULL,
	`age` INT(11) NULL DEFAULT NULL,
	`create_time` VARCHAR(30) NULL DEFAULT NULL,
	`update_time` VARCHAR(30) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `demo_lovers` (
	`id` VARCHAR(32) NOT NULL DEFAULT NULL,
	`name` VARCHAR(45) NULL DEFAULT NULL,
	`boy_id` INT(11) NULL DEFAULT NULL,
	`girl_id` INT(11) NULL DEFAULT NULL,
	`create_time` VARCHAR(30) NULL DEFAULT NULL,
	`update_time` VARCHAR(30) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)